name: Atualizar RSS e gerar index.html

on:
  schedule:
    - cron: '0 * * * *'  # a cada 1 hora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Gerar novo index.html
        run: python gerar_index.py

      - name: Commit e push
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add index.html
          git commit -m "Atualização automática de notícias"
          git push
