name: Commit e push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  commit-e-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Fazer alterações (exemplo)
        run: |
          echo "Exemplo de alteração" >> exemplo.txt

      - name: Adicionar, comitar e push SE houver mudanças
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "Sem alterações para comitar."
          else
            git commit -m "Atualizações automáticas"
            git push
          fi